version: "3.8"
services:
  joao-api-gateway:
    image: joao-api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - "USER_SERVICE_API_URL=http://joao-user-service:3001"
    env_file: ./api-gateway/.env
    container_name: joao-api-gateway-container
    depends_on:
      - joao-user-service
    ports:
      - "3005:3005"
    expose:
      - "3005"
    networks:
      - joao_default
    volumes:
      - "./api-gateway/src/:/usr/src/app/src"


  joao-user-service:
    image: joao-user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
      
    env_file: ./user-service/.env
    container_name: joao-api-user-service 
    networks:
      - joao_default
    expose:
      - "3001"
networks:
     joao_default: {}