version: "3.8"
services:

  rabbitmq-queue-service:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 3s
      timeout: 10s
      retries: 5
    networks:
    - joao_default
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672"
      - "15672"

  joao-api-gateway:
    image: joao-api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - "USER_SERVICE_API_URL=http://joao-user-service:3001"
      - "PROBLEMS_SERVICE_URL=http://problems-service:3002"
      - "CHAT_SERVICE_URL=http://chat-service:3003"
      - "API_GATEWAY_PORT=3005"
    env_file: ./api-gateway/.env
    container_name: joao-api-gateway-container
    depends_on:
      - joao-user-service
      - rabbitmq-queue-service
    ports:
      - "3005:3005"
    expose:
      - "3005"
    networks:
      - joao_default
    volumes:
      - "./api-gateway/src/:/usr/src/app/src"

  joao-user-service:
    image: joao-user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - "PORT=3001"
    env_file: ./user-service/.env
    container_name: joao-api-user-service 
    depends_on:
      mongodb:
        condition: service_started
      mongo_seed:
        condition: service_started
    networks:
      - joao_default
    expose:
      - "3001"

  problems-service:
    image: joao-problems-service
    build:
      context: ./problems-service
      dockerfile: Dockerfile
    environment:
      - "RABBIT_URL=amqp://rabbitmq-queue-service:5672"
      - "PORT=3002"
    env_file: ./problems-service/.env
    container_name: joao-api-problems-service 
    depends_on:
      rabbitmq-queue-service:
        condition: service_healthy
      joao-user-service:
         condition: service_started
      mongodb:
        condition: service_started
      mongo_seed:
        condition: service_started
    networks:
      - joao_default
    expose:
      - "3002"
    
  executer-service:
    image: joao-executer-service
    build:
      context: ./executer-service
      dockerfile: Dockerfile
    environment:
      - "RABBIT_URL=amqp://rabbitmq-queue-service:5672"
    env_file: ./executer-service/.env
    container_name: joao-api-executer-service
    depends_on:
      rabbitmq-queue-service:
        condition: service_healthy
      mongodb:
        condition: service_started
      mongo_seed:
        condition: service_started
    networks:
      - joao_default

  chat-service:
    image: joao-chat-service
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    environment:
      - "RABBIT_URL=amqp://rabbitmq-queue-service:5672"
      - "PORT=3003"
    env_file: ./chat-service/.env
    container_name: joao-api-chat-service
    depends_on:
      rabbitmq-queue-service:
        condition: service_healthy
      mongodb:
        condition: service_started
      mongo_seed:
        condition: service_started
    expose:
      - "3003"
    networks:
      - joao_default

  mongodb:
    image: mongo
    container_name: mongo_db_joao
      
    volumes:
      - ./mongo-docker/mongo-data:/data/db
    ports:
      - 27017:27017
    env_file: ./mongo-docker/.env
    networks:
      - joao_default

  mongo_seed:
    restart: 'no'
#
    build:
      context: ./mongo-docker
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
        
    networks:
      - joao_default
    env_file: ./mongo-docker/.env
networks:
     joao_default: {}